# Generated by Django 6.0.4 on 2026-04-29 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoLoginProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gologin_profile_id', models.CharField(blank=True, help_text='ID from GoLogin API', max_length=255, null=True, unique=True)),
                ('os_type', models.CharField(choices=[('win', 'Windows'), ('mac', 'macOS'), ('lin', 'Linux')], default='win', max_length=10)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('launching', 'Launching'), ('active', 'Active'), ('error', 'Error')], default='inactive', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('proxy', models.JSONField(blank=True, default=dict, help_text='{"mode":"http","host":"","port":8080,"username":"","password":""}')),
                ('extra_config', models.JSONField(blank=True, default=dict, help_text='Additional GoLogin profile configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_launched_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gologin_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GoLogin Profile',
                'ordering': ['-created_at'],
            },
        ),
    ]
