# Generated by Django 6.0.4 on 2026-05-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gologinprofile',
            name='business_context',
            field=models.TextField(blank=True, help_text="Describe your business so AI can reply in context. Example: 'We sell CRM software at $49/month. Demo available. Support: Mon-Sat 9am-6pm IST.'"),
        ),
    ]
