# Generated by Django 6.0.4 on 2026-04-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='delay_seconds',
        ),
        migrations.AddField(
            model_name='campaign',
            name='allowed_time_windows',
            field=models.JSONField(blank=True, default=list, help_text='List of allowed sending windows. Leave empty to use default (8-11am, 1-4pm, 7-10pm). Format: [{"start":"08:00","end":"11:00"},{"start":"13:00","end":"16:00"}]'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_timezone',
            field=models.CharField(default='Asia/Kolkata', help_text='Timezone for time windows. E.g. Asia/Kolkata, UTC, America/New_York', max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='max_delay_seconds',
            field=models.PositiveIntegerField(default=240, help_text='Maximum seconds to wait between messages (default 4 min)'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='min_delay_seconds',
            field=models.PositiveIntegerField(default=180, help_text='Minimum seconds to wait between messages (default 3 min)'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='respect_time_windows',
            field=models.BooleanField(default=True, help_text='Only send messages during allowed_time_windows hours'),
        ),
    ]
