# Generated by Django 6.0.4 on 2026-04-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_remove_campaign_delay_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='auto_send',
            field=models.BooleanField(default=False, help_text='When ON, every new contact added by this owner is automatically messaged via this campaign in real time (no human action needed).'),
        ),
    ]
