# Generated by Django 6.0.4 on 2026-05-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='whatsapp_jid',
            field=models.CharField(blank=True, db_index=True, help_text='Stable WhatsApp JID, e.g. 12025550123@c.us', max_length=100),
        ),
    ]
