# Generated by Django 6.0.4 on 2026-05-08 15:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('whatsapp_sessions', '0002_conversation_incomingmessage_jid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('ai', 'AI'), ('human', 'Human'), ('system', 'System')], max_length=20)),
                ('text', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=60)),
                ('language', models.CharField(blank=True, max_length=20)),
                ('external_message_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_messages', to='whatsapp_sessions.conversation')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AIReplyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_hash', models.CharField(max_length=64)),
                ('reply_text', models.TextField(blank=True)),
                ('skipped_reason', models.CharField(blank=True, max_length=120)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reply_logs', to='whatsapp_sessions.conversation')),
                ('user_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_reply_logs', to='autoreply.conversationmessage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('greeting', 'Greeting'), ('problem_discovery', 'Problem Discovery'), ('current_strategy', 'Current Strategy'), ('service_matching', 'Service Matching'), ('lead_capture', 'Lead Capture'), ('cta', 'CTA'), ('human_handoff', 'Human Handoff')], default='greeting', max_length=40)),
                ('detected_language', models.CharField(default='english', max_length=20)),
                ('last_intent', models.CharField(blank=True, max_length=60)),
                ('last_question_key', models.CharField(blank=True, max_length=80)),
                ('last_ai_reply_at', models.DateTimeField(blank=True, null=True)),
                ('human_active', models.BooleanField(default=False)),
                ('ai_paused_until', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_state', to='whatsapp_sessions.conversation')),
            ],
            options={
                'verbose_name': 'Conversation State',
            },
        ),
        migrations.CreateModel(
            name='HandoffEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=120)),
                ('requested_by', models.CharField(default='ai', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoff_events', to='whatsapp_sessions.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('business_type', models.CharField(blank=True, max_length=255)),
                ('main_problem', models.CharField(blank=True, max_length=120)),
                ('current_marketing_method', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('matched_service', models.CharField(blank=True, max_length=120)),
                ('qualification_score', models.PositiveSmallIntegerField(default=0)),
                ('is_qualified', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_profile', to='whatsapp_sessions.conversation')),
            ],
            options={
                'verbose_name': 'Lead Profile',
            },
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='autoreply_c_convers_0e0566_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['external_message_id'], name='autoreply_c_externa_9fd698_idx'),
        ),
    ]
