# Generated by Django 6.0.4 on 2026-04-29 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('qr_required', 'QR Required'), ('logged_in', 'Logged In'), ('logged_out', 'Logged Out'), ('error', 'Error')], default='pending', max_length=20)),
                ('phone_number', models.CharField(blank=True, help_text='WhatsApp number associated with this session', max_length=20)),
                ('qr_code_base64', models.TextField(blank=True, help_text='Base64-encoded QR code PNG (temporary, for login)')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('logged_in_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_session', to='profiles.gologinprofile')),
            ],
            options={
                'verbose_name': 'WhatsApp Session',
            },
        ),
        migrations.CreateModel(
            name='IncomingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, help_text='Display name shown in WhatsApp sidebar', max_length=255)),
                ('sender_phone', models.CharField(blank=True, help_text='Phone number if extractable, else empty', max_length=20)),
                ('message_preview', models.TextField(help_text='Last message text visible in the chat sidebar')),
                ('unread_count', models.PositiveIntegerField(default=1)),
                ('is_processed', models.BooleanField(default=False, help_text='Mark True once you have read/handled this message')),
                ('received_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_messages', to='whatsapp_sessions.whatsappsession')),
            ],
            options={
                'verbose_name': 'Incoming Message',
                'verbose_name_plural': 'Incoming Messages',
                'ordering': ['-received_at'],
            },
        ),
    ]
